"use client";
import { useState } from "react";
import { Outfit } from "next/font/google";
import "./globals.css";

// components
import Header from "@/components/header/Header";
import Footer from "@/components/Footer";
import BackToTopButton from "@/components/BackToTopButton";
import Chatbot from "@/components/Chatbot";
import WelcomeScreen from "@/components/WelcomeScreen";
import { Toaster } from "@/components/ui/toaster";

// theme provider
import { ThemeProvider } from "@/components/ui/ThemeProvider";
import { LoadingStateProvider } from "@/components/ui/LoadingStateProvider";
import AOSInitializer from "@/components/ui/AOSInitializer";

const outfit = Outfit({ subsets: ["latin"] });

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: "no",
};

export default function RootLayout({ children }) {
  const [showWelcome, setShowWelcome] = useState(true);

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <title>Portfolio - Gilvan</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body className={outfit.className}>
        <ThemeProvider attribute="class" defaultTheme="light">
          <LoadingStateProvider>
            <AOSInitializer />
            {showWelcome ? (
              <WelcomeScreen onLoadingComplete={() => setShowWelcome(false)} />
            ) : (
              <>
                <Header />
                {children}
                <Footer />
                <Chatbot />
                <BackToTopButton />
                <Toaster />
              </>
            )}
          </LoadingStateProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
